# Generated by Django 3.2.25 on 2024-06-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_item', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('quantidade_recebida', models.IntegerField(blank=True, default=0, null=True)),
                ('recebida_por', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade_problema', models.IntegerField(blank=True, default=0, null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroTelfone', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('exportar_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
