# Generated by Django 3.2.25 on 2024-06-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0002_rename_numerotelfone_stock_numerotelefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='Categoria',
        ),
    ]
