# Generated by Django 3.2.25 on 2024-06-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0003_rename_category_stock_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
