# Generated by Django 3.2.25 on 2024-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0006_auto_20240609_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='Categoria',
            field=models.CharField(blank=True, choices=[('Roupas', 'Roupas'), ('Eletrônicos', 'Eletrônicos'), ('Acessórios', 'Acessório'), ('Pereféricos', 'Pereféricos')], max_length=50, null=True),
        ),
    ]
