# Generated by Django 3.2.25 on 2024-06-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0007_auto_20240609_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Estoque.categoria'),
            preserve_default=False,
        ),
    ]
