# Generated by Django 3.2.25 on 2024-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_auth_app', '0003_auto_20240613_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojista',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
